#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SALON")]
	public partial class SALONDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAngajati(Angajati instance);
    partial void UpdateAngajati(Angajati instance);
    partial void DeleteAngajati(Angajati instance);
    partial void InsertServicii(Servicii instance);
    partial void UpdateServicii(Servicii instance);
    partial void DeleteServicii(Servicii instance);
    partial void InsertAngajati_Servicii(Angajati_Servicii instance);
    partial void UpdateAngajati_Servicii(Angajati_Servicii instance);
    partial void DeleteAngajati_Servicii(Angajati_Servicii instance);
    partial void InsertClienti(Clienti instance);
    partial void UpdateClienti(Clienti instance);
    partial void DeleteClienti(Clienti instance);
    partial void InsertDepartamente(Departamente instance);
    partial void UpdateDepartamente(Departamente instance);
    partial void DeleteDepartamente(Departamente instance);
    partial void InsertFunctii(Functii instance);
    partial void UpdateFunctii(Functii instance);
    partial void DeleteFunctii(Functii instance);
    partial void InsertIstoric_Clienti(Istoric_Clienti instance);
    partial void UpdateIstoric_Clienti(Istoric_Clienti instance);
    partial void DeleteIstoric_Clienti(Istoric_Clienti instance);
    partial void InsertPreferinte(Preferinte instance);
    partial void UpdatePreferinte(Preferinte instance);
    partial void DeletePreferinte(Preferinte instance);
    partial void InsertProduse_Cosmetice(Produse_Cosmetice instance);
    partial void UpdateProduse_Cosmetice(Produse_Cosmetice instance);
    partial void DeleteProduse_Cosmetice(Produse_Cosmetice instance);
    partial void InsertProgramari(Programari instance);
    partial void UpdateProgramari(Programari instance);
    partial void DeleteProgramari(Programari instance);
    partial void InsertAngajati_Functii_Departamente(Angajati_Functii_Departamente instance);
    partial void UpdateAngajati_Functii_Departamente(Angajati_Functii_Departamente instance);
    partial void DeleteAngajati_Functii_Departamente(Angajati_Functii_Departamente instance);
    #endregion
		
		public SALONDataContext() : 
				base(global::Proiect.Properties.Settings.Default.SALONConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SALONDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SALONDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SALONDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SALONDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Angajati> Angajatis
		{
			get
			{
				return this.GetTable<Angajati>();
			}
		}
		
		public System.Data.Linq.Table<Servicii> Serviciis
		{
			get
			{
				return this.GetTable<Servicii>();
			}
		}
		
		public System.Data.Linq.Table<Angajati_Servicii> Angajati_Serviciis
		{
			get
			{
				return this.GetTable<Angajati_Servicii>();
			}
		}
		
		public System.Data.Linq.Table<Clienti> Clientis
		{
			get
			{
				return this.GetTable<Clienti>();
			}
		}
		
		public System.Data.Linq.Table<Departamente> Departamentes
		{
			get
			{
				return this.GetTable<Departamente>();
			}
		}
		
		public System.Data.Linq.Table<Functii> Functiis
		{
			get
			{
				return this.GetTable<Functii>();
			}
		}
		
		public System.Data.Linq.Table<Istoric_Clienti> Istoric_Clientis
		{
			get
			{
				return this.GetTable<Istoric_Clienti>();
			}
		}
		
		public System.Data.Linq.Table<Preferinte> Preferintes
		{
			get
			{
				return this.GetTable<Preferinte>();
			}
		}
		
		public System.Data.Linq.Table<Produse_Cosmetice> Produse_Cosmetices
		{
			get
			{
				return this.GetTable<Produse_Cosmetice>();
			}
		}
		
		public System.Data.Linq.Table<Programari> Programaris
		{
			get
			{
				return this.GetTable<Programari>();
			}
		}
		
		public System.Data.Linq.Table<Angajati_Functii_Departamente> Angajati_Functii_Departamentes
		{
			get
			{
				return this.GetTable<Angajati_Functii_Departamente>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Angajati")]
	public partial class Angajati : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Angajat;
		
		private string _Nume;
		
		private string _Prenume;
		
		private System.Nullable<System.DateTime> _Data_Nasterii;
		
		private System.Nullable<System.DateTime> _Data_Angajarii;
		
		private string _Adresa;
		
		private string _Oras;
		
		private string _Email;
		
		private string _Parola;
		
		private EntitySet<Angajati_Servicii> _Angajati_Serviciis;
		
		private EntitySet<Programari> _Programaris;
		
		private EntitySet<Angajati_Functii_Departamente> _Angajati_Functii_Departamentes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_AngajatChanging(int value);
    partial void OnID_AngajatChanged();
    partial void OnNumeChanging(string value);
    partial void OnNumeChanged();
    partial void OnPrenumeChanging(string value);
    partial void OnPrenumeChanged();
    partial void OnData_NasteriiChanging(System.Nullable<System.DateTime> value);
    partial void OnData_NasteriiChanged();
    partial void OnData_AngajariiChanging(System.Nullable<System.DateTime> value);
    partial void OnData_AngajariiChanged();
    partial void OnAdresaChanging(string value);
    partial void OnAdresaChanged();
    partial void OnOrasChanging(string value);
    partial void OnOrasChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnParolaChanging(string value);
    partial void OnParolaChanged();
    #endregion
		
		public Angajati()
		{
			this._Angajati_Serviciis = new EntitySet<Angajati_Servicii>(new Action<Angajati_Servicii>(this.attach_Angajati_Serviciis), new Action<Angajati_Servicii>(this.detach_Angajati_Serviciis));
			this._Programaris = new EntitySet<Programari>(new Action<Programari>(this.attach_Programaris), new Action<Programari>(this.detach_Programaris));
			this._Angajati_Functii_Departamentes = new EntitySet<Angajati_Functii_Departamente>(new Action<Angajati_Functii_Departamente>(this.attach_Angajati_Functii_Departamentes), new Action<Angajati_Functii_Departamente>(this.detach_Angajati_Functii_Departamentes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Angajat", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Angajat
		{
			get
			{
				return this._ID_Angajat;
			}
			set
			{
				if ((this._ID_Angajat != value))
				{
					this.OnID_AngajatChanging(value);
					this.SendPropertyChanging();
					this._ID_Angajat = value;
					this.SendPropertyChanged("ID_Angajat");
					this.OnID_AngajatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this.OnNumeChanging(value);
					this.SendPropertyChanging();
					this._Nume = value;
					this.SendPropertyChanged("Nume");
					this.OnNumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenume", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Prenume
		{
			get
			{
				return this._Prenume;
			}
			set
			{
				if ((this._Prenume != value))
				{
					this.OnPrenumeChanging(value);
					this.SendPropertyChanging();
					this._Prenume = value;
					this.SendPropertyChanged("Prenume");
					this.OnPrenumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_Nasterii", DbType="DateTime")]
		public System.Nullable<System.DateTime> Data_Nasterii
		{
			get
			{
				return this._Data_Nasterii;
			}
			set
			{
				if ((this._Data_Nasterii != value))
				{
					this.OnData_NasteriiChanging(value);
					this.SendPropertyChanging();
					this._Data_Nasterii = value;
					this.SendPropertyChanged("Data_Nasterii");
					this.OnData_NasteriiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_Angajarii", DbType="DateTime")]
		public System.Nullable<System.DateTime> Data_Angajarii
		{
			get
			{
				return this._Data_Angajarii;
			}
			set
			{
				if ((this._Data_Angajarii != value))
				{
					this.OnData_AngajariiChanging(value);
					this.SendPropertyChanging();
					this._Data_Angajarii = value;
					this.SendPropertyChanged("Data_Angajarii");
					this.OnData_AngajariiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresa", DbType="NVarChar(60)")]
		public string Adresa
		{
			get
			{
				return this._Adresa;
			}
			set
			{
				if ((this._Adresa != value))
				{
					this.OnAdresaChanging(value);
					this.SendPropertyChanging();
					this._Adresa = value;
					this.SendPropertyChanged("Adresa");
					this.OnAdresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oras", DbType="VarChar(50)")]
		public string Oras
		{
			get
			{
				return this._Oras;
			}
			set
			{
				if ((this._Oras != value))
				{
					this.OnOrasChanging(value);
					this.SendPropertyChanging();
					this._Oras = value;
					this.SendPropertyChanged("Oras");
					this.OnOrasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parola", DbType="VarChar(30)")]
		public string Parola
		{
			get
			{
				return this._Parola;
			}
			set
			{
				if ((this._Parola != value))
				{
					this.OnParolaChanging(value);
					this.SendPropertyChanging();
					this._Parola = value;
					this.SendPropertyChanged("Parola");
					this.OnParolaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Angajati_Angajati_Servicii", Storage="_Angajati_Serviciis", ThisKey="ID_Angajat", OtherKey="ID_Angajat")]
		public EntitySet<Angajati_Servicii> Angajati_Serviciis
		{
			get
			{
				return this._Angajati_Serviciis;
			}
			set
			{
				this._Angajati_Serviciis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Angajati_Programari", Storage="_Programaris", ThisKey="ID_Angajat", OtherKey="ID_Angajat")]
		public EntitySet<Programari> Programaris
		{
			get
			{
				return this._Programaris;
			}
			set
			{
				this._Programaris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Angajati_Angajati_Functii_Departamente", Storage="_Angajati_Functii_Departamentes", ThisKey="ID_Angajat", OtherKey="ID_Angajat")]
		public EntitySet<Angajati_Functii_Departamente> Angajati_Functii_Departamentes
		{
			get
			{
				return this._Angajati_Functii_Departamentes;
			}
			set
			{
				this._Angajati_Functii_Departamentes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Angajati_Serviciis(Angajati_Servicii entity)
		{
			this.SendPropertyChanging();
			entity.Angajati = this;
		}
		
		private void detach_Angajati_Serviciis(Angajati_Servicii entity)
		{
			this.SendPropertyChanging();
			entity.Angajati = null;
		}
		
		private void attach_Programaris(Programari entity)
		{
			this.SendPropertyChanging();
			entity.Angajati = this;
		}
		
		private void detach_Programaris(Programari entity)
		{
			this.SendPropertyChanging();
			entity.Angajati = null;
		}
		
		private void attach_Angajati_Functii_Departamentes(Angajati_Functii_Departamente entity)
		{
			this.SendPropertyChanging();
			entity.Angajati = this;
		}
		
		private void detach_Angajati_Functii_Departamentes(Angajati_Functii_Departamente entity)
		{
			this.SendPropertyChanging();
			entity.Angajati = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Servicii")]
	public partial class Servicii : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Serviciu;
		
		private string _Denumire;
		
		private double _Pret;
		
		private string _Categorie;
		
		private EntitySet<Angajati_Servicii> _Angajati_Serviciis;
		
		private EntitySet<Programari> _Programaris;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ServiciuChanging(int value);
    partial void OnID_ServiciuChanged();
    partial void OnDenumireChanging(string value);
    partial void OnDenumireChanged();
    partial void OnPretChanging(double value);
    partial void OnPretChanged();
    partial void OnCategorieChanging(string value);
    partial void OnCategorieChanged();
    #endregion
		
		public Servicii()
		{
			this._Angajati_Serviciis = new EntitySet<Angajati_Servicii>(new Action<Angajati_Servicii>(this.attach_Angajati_Serviciis), new Action<Angajati_Servicii>(this.detach_Angajati_Serviciis));
			this._Programaris = new EntitySet<Programari>(new Action<Programari>(this.attach_Programaris), new Action<Programari>(this.detach_Programaris));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Serviciu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Serviciu
		{
			get
			{
				return this._ID_Serviciu;
			}
			set
			{
				if ((this._ID_Serviciu != value))
				{
					this.OnID_ServiciuChanging(value);
					this.SendPropertyChanging();
					this._ID_Serviciu = value;
					this.SendPropertyChanged("ID_Serviciu");
					this.OnID_ServiciuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Denumire", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Denumire
		{
			get
			{
				return this._Denumire;
			}
			set
			{
				if ((this._Denumire != value))
				{
					this.OnDenumireChanging(value);
					this.SendPropertyChanging();
					this._Denumire = value;
					this.SendPropertyChanged("Denumire");
					this.OnDenumireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pret", DbType="Float NOT NULL")]
		public double Pret
		{
			get
			{
				return this._Pret;
			}
			set
			{
				if ((this._Pret != value))
				{
					this.OnPretChanging(value);
					this.SendPropertyChanging();
					this._Pret = value;
					this.SendPropertyChanged("Pret");
					this.OnPretChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categorie", DbType="VarChar(50)")]
		public string Categorie
		{
			get
			{
				return this._Categorie;
			}
			set
			{
				if ((this._Categorie != value))
				{
					this.OnCategorieChanging(value);
					this.SendPropertyChanging();
					this._Categorie = value;
					this.SendPropertyChanged("Categorie");
					this.OnCategorieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Servicii_Angajati_Servicii", Storage="_Angajati_Serviciis", ThisKey="ID_Serviciu", OtherKey="ID_Serviciu")]
		public EntitySet<Angajati_Servicii> Angajati_Serviciis
		{
			get
			{
				return this._Angajati_Serviciis;
			}
			set
			{
				this._Angajati_Serviciis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Servicii_Programari", Storage="_Programaris", ThisKey="ID_Serviciu", OtherKey="ID_Serviciu")]
		public EntitySet<Programari> Programaris
		{
			get
			{
				return this._Programaris;
			}
			set
			{
				this._Programaris.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Angajati_Serviciis(Angajati_Servicii entity)
		{
			this.SendPropertyChanging();
			entity.Servicii = this;
		}
		
		private void detach_Angajati_Serviciis(Angajati_Servicii entity)
		{
			this.SendPropertyChanging();
			entity.Servicii = null;
		}
		
		private void attach_Programaris(Programari entity)
		{
			this.SendPropertyChanging();
			entity.Servicii = this;
		}
		
		private void detach_Programaris(Programari entity)
		{
			this.SendPropertyChanging();
			entity.Servicii = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Angajati_Servicii")]
	public partial class Angajati_Servicii : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_relatie;
		
		private System.Nullable<int> _ID_Angajat;
		
		private System.Nullable<int> _ID_Serviciu;
		
		private EntityRef<Angajati> _Angajati;
		
		private EntityRef<Servicii> _Servicii;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_relatieChanging(int value);
    partial void OnID_relatieChanged();
    partial void OnID_AngajatChanging(System.Nullable<int> value);
    partial void OnID_AngajatChanged();
    partial void OnID_ServiciuChanging(System.Nullable<int> value);
    partial void OnID_ServiciuChanged();
    #endregion
		
		public Angajati_Servicii()
		{
			this._Angajati = default(EntityRef<Angajati>);
			this._Servicii = default(EntityRef<Servicii>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_relatie", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_relatie
		{
			get
			{
				return this._ID_relatie;
			}
			set
			{
				if ((this._ID_relatie != value))
				{
					this.OnID_relatieChanging(value);
					this.SendPropertyChanging();
					this._ID_relatie = value;
					this.SendPropertyChanged("ID_relatie");
					this.OnID_relatieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Angajat", DbType="Int")]
		public System.Nullable<int> ID_Angajat
		{
			get
			{
				return this._ID_Angajat;
			}
			set
			{
				if ((this._ID_Angajat != value))
				{
					if (this._Angajati.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_AngajatChanging(value);
					this.SendPropertyChanging();
					this._ID_Angajat = value;
					this.SendPropertyChanged("ID_Angajat");
					this.OnID_AngajatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Serviciu", DbType="Int")]
		public System.Nullable<int> ID_Serviciu
		{
			get
			{
				return this._ID_Serviciu;
			}
			set
			{
				if ((this._ID_Serviciu != value))
				{
					if (this._Servicii.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ServiciuChanging(value);
					this.SendPropertyChanging();
					this._ID_Serviciu = value;
					this.SendPropertyChanged("ID_Serviciu");
					this.OnID_ServiciuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Angajati_Angajati_Servicii", Storage="_Angajati", ThisKey="ID_Angajat", OtherKey="ID_Angajat", IsForeignKey=true)]
		public Angajati Angajati
		{
			get
			{
				return this._Angajati.Entity;
			}
			set
			{
				Angajati previousValue = this._Angajati.Entity;
				if (((previousValue != value) 
							|| (this._Angajati.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Angajati.Entity = null;
						previousValue.Angajati_Serviciis.Remove(this);
					}
					this._Angajati.Entity = value;
					if ((value != null))
					{
						value.Angajati_Serviciis.Add(this);
						this._ID_Angajat = value.ID_Angajat;
					}
					else
					{
						this._ID_Angajat = default(Nullable<int>);
					}
					this.SendPropertyChanged("Angajati");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Servicii_Angajati_Servicii", Storage="_Servicii", ThisKey="ID_Serviciu", OtherKey="ID_Serviciu", IsForeignKey=true)]
		public Servicii Servicii
		{
			get
			{
				return this._Servicii.Entity;
			}
			set
			{
				Servicii previousValue = this._Servicii.Entity;
				if (((previousValue != value) 
							|| (this._Servicii.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Servicii.Entity = null;
						previousValue.Angajati_Serviciis.Remove(this);
					}
					this._Servicii.Entity = value;
					if ((value != null))
					{
						value.Angajati_Serviciis.Add(this);
						this._ID_Serviciu = value.ID_Serviciu;
					}
					else
					{
						this._ID_Serviciu = default(Nullable<int>);
					}
					this.SendPropertyChanged("Servicii");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clienti")]
	public partial class Clienti : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Client;
		
		private string _Nume;
		
		private string _Prenume;
		
		private string _Telefon;
		
		private string _Email;
		
		private string _Parola;
		
		private string _Gen;
		
		private EntitySet<Istoric_Clienti> _Istoric_Clientis;
		
		private EntitySet<Programari> _Programaris;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ClientChanging(int value);
    partial void OnID_ClientChanged();
    partial void OnNumeChanging(string value);
    partial void OnNumeChanged();
    partial void OnPrenumeChanging(string value);
    partial void OnPrenumeChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnParolaChanging(string value);
    partial void OnParolaChanged();
    partial void OnGenChanging(string value);
    partial void OnGenChanged();
    #endregion
		
		public Clienti()
		{
			this._Istoric_Clientis = new EntitySet<Istoric_Clienti>(new Action<Istoric_Clienti>(this.attach_Istoric_Clientis), new Action<Istoric_Clienti>(this.detach_Istoric_Clientis));
			this._Programaris = new EntitySet<Programari>(new Action<Programari>(this.attach_Programaris), new Action<Programari>(this.detach_Programaris));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Client", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Client
		{
			get
			{
				return this._ID_Client;
			}
			set
			{
				if ((this._ID_Client != value))
				{
					this.OnID_ClientChanging(value);
					this.SendPropertyChanging();
					this._ID_Client = value;
					this.SendPropertyChanged("ID_Client");
					this.OnID_ClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nume", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nume
		{
			get
			{
				return this._Nume;
			}
			set
			{
				if ((this._Nume != value))
				{
					this.OnNumeChanging(value);
					this.SendPropertyChanging();
					this._Nume = value;
					this.SendPropertyChanged("Nume");
					this.OnNumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenume", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Prenume
		{
			get
			{
				return this._Prenume;
			}
			set
			{
				if ((this._Prenume != value))
				{
					this.OnPrenumeChanging(value);
					this.SendPropertyChanging();
					this._Prenume = value;
					this.SendPropertyChanged("Prenume");
					this.OnPrenumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="VarChar(10)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parola", DbType="VarChar(30)")]
		public string Parola
		{
			get
			{
				return this._Parola;
			}
			set
			{
				if ((this._Parola != value))
				{
					this.OnParolaChanging(value);
					this.SendPropertyChanging();
					this._Parola = value;
					this.SendPropertyChanged("Parola");
					this.OnParolaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gen", DbType="VarChar(1)")]
		public string Gen
		{
			get
			{
				return this._Gen;
			}
			set
			{
				if ((this._Gen != value))
				{
					this.OnGenChanging(value);
					this.SendPropertyChanging();
					this._Gen = value;
					this.SendPropertyChanged("Gen");
					this.OnGenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Clienti_Istoric_Clienti", Storage="_Istoric_Clientis", ThisKey="ID_Client", OtherKey="ID_Client")]
		public EntitySet<Istoric_Clienti> Istoric_Clientis
		{
			get
			{
				return this._Istoric_Clientis;
			}
			set
			{
				this._Istoric_Clientis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Clienti_Programari", Storage="_Programaris", ThisKey="ID_Client", OtherKey="ID_Client")]
		public EntitySet<Programari> Programaris
		{
			get
			{
				return this._Programaris;
			}
			set
			{
				this._Programaris.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Istoric_Clientis(Istoric_Clienti entity)
		{
			this.SendPropertyChanging();
			entity.Clienti = this;
		}
		
		private void detach_Istoric_Clientis(Istoric_Clienti entity)
		{
			this.SendPropertyChanging();
			entity.Clienti = null;
		}
		
		private void attach_Programaris(Programari entity)
		{
			this.SendPropertyChanging();
			entity.Clienti = this;
		}
		
		private void detach_Programaris(Programari entity)
		{
			this.SendPropertyChanging();
			entity.Clienti = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Departamente")]
	public partial class Departamente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_departament;
		
		private string _Denumire;
		
		private EntitySet<Angajati_Functii_Departamente> _Angajati_Functii_Departamentes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_departamentChanging(int value);
    partial void OnID_departamentChanged();
    partial void OnDenumireChanging(string value);
    partial void OnDenumireChanged();
    #endregion
		
		public Departamente()
		{
			this._Angajati_Functii_Departamentes = new EntitySet<Angajati_Functii_Departamente>(new Action<Angajati_Functii_Departamente>(this.attach_Angajati_Functii_Departamentes), new Action<Angajati_Functii_Departamente>(this.detach_Angajati_Functii_Departamentes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_departament", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_departament
		{
			get
			{
				return this._ID_departament;
			}
			set
			{
				if ((this._ID_departament != value))
				{
					this.OnID_departamentChanging(value);
					this.SendPropertyChanging();
					this._ID_departament = value;
					this.SendPropertyChanged("ID_departament");
					this.OnID_departamentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Denumire", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Denumire
		{
			get
			{
				return this._Denumire;
			}
			set
			{
				if ((this._Denumire != value))
				{
					this.OnDenumireChanging(value);
					this.SendPropertyChanging();
					this._Denumire = value;
					this.SendPropertyChanged("Denumire");
					this.OnDenumireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamente_Angajati_Functii_Departamente", Storage="_Angajati_Functii_Departamentes", ThisKey="ID_departament", OtherKey="ID_Departament")]
		public EntitySet<Angajati_Functii_Departamente> Angajati_Functii_Departamentes
		{
			get
			{
				return this._Angajati_Functii_Departamentes;
			}
			set
			{
				this._Angajati_Functii_Departamentes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Angajati_Functii_Departamentes(Angajati_Functii_Departamente entity)
		{
			this.SendPropertyChanging();
			entity.Departamente = this;
		}
		
		private void detach_Angajati_Functii_Departamentes(Angajati_Functii_Departamente entity)
		{
			this.SendPropertyChanging();
			entity.Departamente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Functii")]
	public partial class Functii : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Functie;
		
		private string _Denumire;
		
		private EntitySet<Angajati_Functii_Departamente> _Angajati_Functii_Departamentes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_FunctieChanging(int value);
    partial void OnID_FunctieChanged();
    partial void OnDenumireChanging(string value);
    partial void OnDenumireChanged();
    #endregion
		
		public Functii()
		{
			this._Angajati_Functii_Departamentes = new EntitySet<Angajati_Functii_Departamente>(new Action<Angajati_Functii_Departamente>(this.attach_Angajati_Functii_Departamentes), new Action<Angajati_Functii_Departamente>(this.detach_Angajati_Functii_Departamentes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Functie", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Functie
		{
			get
			{
				return this._ID_Functie;
			}
			set
			{
				if ((this._ID_Functie != value))
				{
					this.OnID_FunctieChanging(value);
					this.SendPropertyChanging();
					this._ID_Functie = value;
					this.SendPropertyChanged("ID_Functie");
					this.OnID_FunctieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Denumire", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Denumire
		{
			get
			{
				return this._Denumire;
			}
			set
			{
				if ((this._Denumire != value))
				{
					this.OnDenumireChanging(value);
					this.SendPropertyChanging();
					this._Denumire = value;
					this.SendPropertyChanged("Denumire");
					this.OnDenumireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Functii_Angajati_Functii_Departamente", Storage="_Angajati_Functii_Departamentes", ThisKey="ID_Functie", OtherKey="ID_Functie")]
		public EntitySet<Angajati_Functii_Departamente> Angajati_Functii_Departamentes
		{
			get
			{
				return this._Angajati_Functii_Departamentes;
			}
			set
			{
				this._Angajati_Functii_Departamentes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Angajati_Functii_Departamentes(Angajati_Functii_Departamente entity)
		{
			this.SendPropertyChanging();
			entity.Functii = this;
		}
		
		private void detach_Angajati_Functii_Departamentes(Angajati_Functii_Departamente entity)
		{
			this.SendPropertyChanging();
			entity.Functii = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Istoric_Clienti")]
	public partial class Istoric_Clienti : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Istoric;
		
		private System.Nullable<int> _ID_Client;
		
		private System.Nullable<int> _ID_Programare;
		
		private string _Recenzie;
		
		private System.Nullable<int> _Nota;
		
		private EntityRef<Clienti> _Clienti;
		
		private EntityRef<Programari> _Programari;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_IstoricChanging(int value);
    partial void OnID_IstoricChanged();
    partial void OnID_ClientChanging(System.Nullable<int> value);
    partial void OnID_ClientChanged();
    partial void OnID_ProgramareChanging(System.Nullable<int> value);
    partial void OnID_ProgramareChanged();
    partial void OnRecenzieChanging(string value);
    partial void OnRecenzieChanged();
    partial void OnNotaChanging(System.Nullable<int> value);
    partial void OnNotaChanged();
    #endregion
		
		public Istoric_Clienti()
		{
			this._Clienti = default(EntityRef<Clienti>);
			this._Programari = default(EntityRef<Programari>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Istoric", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Istoric
		{
			get
			{
				return this._ID_Istoric;
			}
			set
			{
				if ((this._ID_Istoric != value))
				{
					this.OnID_IstoricChanging(value);
					this.SendPropertyChanging();
					this._ID_Istoric = value;
					this.SendPropertyChanged("ID_Istoric");
					this.OnID_IstoricChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Client", DbType="Int")]
		public System.Nullable<int> ID_Client
		{
			get
			{
				return this._ID_Client;
			}
			set
			{
				if ((this._ID_Client != value))
				{
					if (this._Clienti.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ClientChanging(value);
					this.SendPropertyChanging();
					this._ID_Client = value;
					this.SendPropertyChanged("ID_Client");
					this.OnID_ClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Programare", DbType="Int")]
		public System.Nullable<int> ID_Programare
		{
			get
			{
				return this._ID_Programare;
			}
			set
			{
				if ((this._ID_Programare != value))
				{
					if (this._Programari.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ProgramareChanging(value);
					this.SendPropertyChanging();
					this._ID_Programare = value;
					this.SendPropertyChanged("ID_Programare");
					this.OnID_ProgramareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recenzie", DbType="VarChar(200)")]
		public string Recenzie
		{
			get
			{
				return this._Recenzie;
			}
			set
			{
				if ((this._Recenzie != value))
				{
					this.OnRecenzieChanging(value);
					this.SendPropertyChanging();
					this._Recenzie = value;
					this.SendPropertyChanged("Recenzie");
					this.OnRecenzieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nota", DbType="Int")]
		public System.Nullable<int> Nota
		{
			get
			{
				return this._Nota;
			}
			set
			{
				if ((this._Nota != value))
				{
					this.OnNotaChanging(value);
					this.SendPropertyChanging();
					this._Nota = value;
					this.SendPropertyChanged("Nota");
					this.OnNotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Clienti_Istoric_Clienti", Storage="_Clienti", ThisKey="ID_Client", OtherKey="ID_Client", IsForeignKey=true)]
		public Clienti Clienti
		{
			get
			{
				return this._Clienti.Entity;
			}
			set
			{
				Clienti previousValue = this._Clienti.Entity;
				if (((previousValue != value) 
							|| (this._Clienti.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Clienti.Entity = null;
						previousValue.Istoric_Clientis.Remove(this);
					}
					this._Clienti.Entity = value;
					if ((value != null))
					{
						value.Istoric_Clientis.Add(this);
						this._ID_Client = value.ID_Client;
					}
					else
					{
						this._ID_Client = default(Nullable<int>);
					}
					this.SendPropertyChanged("Clienti");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Programari_Istoric_Clienti", Storage="_Programari", ThisKey="ID_Programare", OtherKey="ID_Programare", IsForeignKey=true)]
		public Programari Programari
		{
			get
			{
				return this._Programari.Entity;
			}
			set
			{
				Programari previousValue = this._Programari.Entity;
				if (((previousValue != value) 
							|| (this._Programari.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Programari.Entity = null;
						previousValue.Istoric_Clientis.Remove(this);
					}
					this._Programari.Entity = value;
					if ((value != null))
					{
						value.Istoric_Clientis.Add(this);
						this._ID_Programare = value.ID_Programare;
					}
					else
					{
						this._ID_Programare = default(Nullable<int>);
					}
					this.SendPropertyChanged("Programari");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Preferinte")]
	public partial class Preferinte : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Preferinta;
		
		private System.Nullable<int> _ID_Programare;
		
		private string _Detalii_Preferinta;
		
		private EntityRef<Programari> _Programari;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PreferintaChanging(int value);
    partial void OnID_PreferintaChanged();
    partial void OnID_ProgramareChanging(System.Nullable<int> value);
    partial void OnID_ProgramareChanged();
    partial void OnDetalii_PreferintaChanging(string value);
    partial void OnDetalii_PreferintaChanged();
    #endregion
		
		public Preferinte()
		{
			this._Programari = default(EntityRef<Programari>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Preferinta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Preferinta
		{
			get
			{
				return this._ID_Preferinta;
			}
			set
			{
				if ((this._ID_Preferinta != value))
				{
					this.OnID_PreferintaChanging(value);
					this.SendPropertyChanging();
					this._ID_Preferinta = value;
					this.SendPropertyChanged("ID_Preferinta");
					this.OnID_PreferintaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Programare", DbType="Int")]
		public System.Nullable<int> ID_Programare
		{
			get
			{
				return this._ID_Programare;
			}
			set
			{
				if ((this._ID_Programare != value))
				{
					if (this._Programari.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ProgramareChanging(value);
					this.SendPropertyChanging();
					this._ID_Programare = value;
					this.SendPropertyChanged("ID_Programare");
					this.OnID_ProgramareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalii_Preferinta", DbType="VarChar(255)")]
		public string Detalii_Preferinta
		{
			get
			{
				return this._Detalii_Preferinta;
			}
			set
			{
				if ((this._Detalii_Preferinta != value))
				{
					this.OnDetalii_PreferintaChanging(value);
					this.SendPropertyChanging();
					this._Detalii_Preferinta = value;
					this.SendPropertyChanged("Detalii_Preferinta");
					this.OnDetalii_PreferintaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Programari_Preferinte", Storage="_Programari", ThisKey="ID_Programare", OtherKey="ID_Programare", IsForeignKey=true)]
		public Programari Programari
		{
			get
			{
				return this._Programari.Entity;
			}
			set
			{
				Programari previousValue = this._Programari.Entity;
				if (((previousValue != value) 
							|| (this._Programari.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Programari.Entity = null;
						previousValue.Preferintes.Remove(this);
					}
					this._Programari.Entity = value;
					if ((value != null))
					{
						value.Preferintes.Add(this);
						this._ID_Programare = value.ID_Programare;
					}
					else
					{
						this._ID_Programare = default(Nullable<int>);
					}
					this.SendPropertyChanged("Programari");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produse_Cosmetice")]
	public partial class Produse_Cosmetice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Produs;
		
		private string _Denumire;
		
		private int _CantitaeInStoc;
		
		private System.Nullable<double> _PretBucata;
		
		private string _Furnizor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ProdusChanging(int value);
    partial void OnID_ProdusChanged();
    partial void OnDenumireChanging(string value);
    partial void OnDenumireChanged();
    partial void OnCantitaeInStocChanging(int value);
    partial void OnCantitaeInStocChanged();
    partial void OnPretBucataChanging(System.Nullable<double> value);
    partial void OnPretBucataChanged();
    partial void OnFurnizorChanging(string value);
    partial void OnFurnizorChanged();
    #endregion
		
		public Produse_Cosmetice()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Produs", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Produs
		{
			get
			{
				return this._ID_Produs;
			}
			set
			{
				if ((this._ID_Produs != value))
				{
					this.OnID_ProdusChanging(value);
					this.SendPropertyChanging();
					this._ID_Produs = value;
					this.SendPropertyChanged("ID_Produs");
					this.OnID_ProdusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Denumire", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Denumire
		{
			get
			{
				return this._Denumire;
			}
			set
			{
				if ((this._Denumire != value))
				{
					this.OnDenumireChanging(value);
					this.SendPropertyChanging();
					this._Denumire = value;
					this.SendPropertyChanged("Denumire");
					this.OnDenumireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantitaeInStoc", DbType="Int NOT NULL")]
		public int CantitaeInStoc
		{
			get
			{
				return this._CantitaeInStoc;
			}
			set
			{
				if ((this._CantitaeInStoc != value))
				{
					this.OnCantitaeInStocChanging(value);
					this.SendPropertyChanging();
					this._CantitaeInStoc = value;
					this.SendPropertyChanged("CantitaeInStoc");
					this.OnCantitaeInStocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PretBucata", DbType="Float")]
		public System.Nullable<double> PretBucata
		{
			get
			{
				return this._PretBucata;
			}
			set
			{
				if ((this._PretBucata != value))
				{
					this.OnPretBucataChanging(value);
					this.SendPropertyChanging();
					this._PretBucata = value;
					this.SendPropertyChanged("PretBucata");
					this.OnPretBucataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Furnizor", DbType="VarChar(30)")]
		public string Furnizor
		{
			get
			{
				return this._Furnizor;
			}
			set
			{
				if ((this._Furnizor != value))
				{
					this.OnFurnizorChanging(value);
					this.SendPropertyChanging();
					this._Furnizor = value;
					this.SendPropertyChanged("Furnizor");
					this.OnFurnizorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Programari")]
	public partial class Programari : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Programare;
		
		private System.Nullable<int> _ID_Client;
		
		private System.Nullable<int> _ID_Angajat;
		
		private System.Nullable<int> _ID_Serviciu;
		
		private System.DateTime _Data_programare;
		
		private System.TimeSpan _Ora;
		
		private string _Stare;
		
		private EntitySet<Istoric_Clienti> _Istoric_Clientis;
		
		private EntitySet<Preferinte> _Preferintes;
		
		private EntityRef<Angajati> _Angajati;
		
		private EntityRef<Clienti> _Clienti;
		
		private EntityRef<Servicii> _Servicii;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ProgramareChanging(int value);
    partial void OnID_ProgramareChanged();
    partial void OnID_ClientChanging(System.Nullable<int> value);
    partial void OnID_ClientChanged();
    partial void OnID_AngajatChanging(System.Nullable<int> value);
    partial void OnID_AngajatChanged();
    partial void OnID_ServiciuChanging(System.Nullable<int> value);
    partial void OnID_ServiciuChanged();
    partial void OnData_programareChanging(System.DateTime value);
    partial void OnData_programareChanged();
    partial void OnOraChanging(System.TimeSpan value);
    partial void OnOraChanged();
    partial void OnStareChanging(string value);
    partial void OnStareChanged();
    #endregion
		
		public Programari()
		{
			this._Istoric_Clientis = new EntitySet<Istoric_Clienti>(new Action<Istoric_Clienti>(this.attach_Istoric_Clientis), new Action<Istoric_Clienti>(this.detach_Istoric_Clientis));
			this._Preferintes = new EntitySet<Preferinte>(new Action<Preferinte>(this.attach_Preferintes), new Action<Preferinte>(this.detach_Preferintes));
			this._Angajati = default(EntityRef<Angajati>);
			this._Clienti = default(EntityRef<Clienti>);
			this._Servicii = default(EntityRef<Servicii>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Programare", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Programare
		{
			get
			{
				return this._ID_Programare;
			}
			set
			{
				if ((this._ID_Programare != value))
				{
					this.OnID_ProgramareChanging(value);
					this.SendPropertyChanging();
					this._ID_Programare = value;
					this.SendPropertyChanged("ID_Programare");
					this.OnID_ProgramareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Client", DbType="Int")]
		public System.Nullable<int> ID_Client
		{
			get
			{
				return this._ID_Client;
			}
			set
			{
				if ((this._ID_Client != value))
				{
					if (this._Clienti.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ClientChanging(value);
					this.SendPropertyChanging();
					this._ID_Client = value;
					this.SendPropertyChanged("ID_Client");
					this.OnID_ClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Angajat", DbType="Int")]
		public System.Nullable<int> ID_Angajat
		{
			get
			{
				return this._ID_Angajat;
			}
			set
			{
				if ((this._ID_Angajat != value))
				{
					if (this._Angajati.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_AngajatChanging(value);
					this.SendPropertyChanging();
					this._ID_Angajat = value;
					this.SendPropertyChanged("ID_Angajat");
					this.OnID_AngajatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Serviciu", DbType="Int")]
		public System.Nullable<int> ID_Serviciu
		{
			get
			{
				return this._ID_Serviciu;
			}
			set
			{
				if ((this._ID_Serviciu != value))
				{
					if (this._Servicii.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ServiciuChanging(value);
					this.SendPropertyChanging();
					this._ID_Serviciu = value;
					this.SendPropertyChanged("ID_Serviciu");
					this.OnID_ServiciuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_programare", DbType="DateTime NOT NULL")]
		public System.DateTime Data_programare
		{
			get
			{
				return this._Data_programare;
			}
			set
			{
				if ((this._Data_programare != value))
				{
					this.OnData_programareChanging(value);
					this.SendPropertyChanging();
					this._Data_programare = value;
					this.SendPropertyChanged("Data_programare");
					this.OnData_programareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ora", DbType="Time NOT NULL")]
		public System.TimeSpan Ora
		{
			get
			{
				return this._Ora;
			}
			set
			{
				if ((this._Ora != value))
				{
					this.OnOraChanging(value);
					this.SendPropertyChanging();
					this._Ora = value;
					this.SendPropertyChanged("Ora");
					this.OnOraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stare", DbType="VarChar(50)")]
		public string Stare
		{
			get
			{
				return this._Stare;
			}
			set
			{
				if ((this._Stare != value))
				{
					this.OnStareChanging(value);
					this.SendPropertyChanging();
					this._Stare = value;
					this.SendPropertyChanged("Stare");
					this.OnStareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Programari_Istoric_Clienti", Storage="_Istoric_Clientis", ThisKey="ID_Programare", OtherKey="ID_Programare")]
		public EntitySet<Istoric_Clienti> Istoric_Clientis
		{
			get
			{
				return this._Istoric_Clientis;
			}
			set
			{
				this._Istoric_Clientis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Programari_Preferinte", Storage="_Preferintes", ThisKey="ID_Programare", OtherKey="ID_Programare")]
		public EntitySet<Preferinte> Preferintes
		{
			get
			{
				return this._Preferintes;
			}
			set
			{
				this._Preferintes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Angajati_Programari", Storage="_Angajati", ThisKey="ID_Angajat", OtherKey="ID_Angajat", IsForeignKey=true)]
		public Angajati Angajati
		{
			get
			{
				return this._Angajati.Entity;
			}
			set
			{
				Angajati previousValue = this._Angajati.Entity;
				if (((previousValue != value) 
							|| (this._Angajati.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Angajati.Entity = null;
						previousValue.Programaris.Remove(this);
					}
					this._Angajati.Entity = value;
					if ((value != null))
					{
						value.Programaris.Add(this);
						this._ID_Angajat = value.ID_Angajat;
					}
					else
					{
						this._ID_Angajat = default(Nullable<int>);
					}
					this.SendPropertyChanged("Angajati");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Clienti_Programari", Storage="_Clienti", ThisKey="ID_Client", OtherKey="ID_Client", IsForeignKey=true)]
		public Clienti Clienti
		{
			get
			{
				return this._Clienti.Entity;
			}
			set
			{
				Clienti previousValue = this._Clienti.Entity;
				if (((previousValue != value) 
							|| (this._Clienti.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Clienti.Entity = null;
						previousValue.Programaris.Remove(this);
					}
					this._Clienti.Entity = value;
					if ((value != null))
					{
						value.Programaris.Add(this);
						this._ID_Client = value.ID_Client;
					}
					else
					{
						this._ID_Client = default(Nullable<int>);
					}
					this.SendPropertyChanged("Clienti");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Servicii_Programari", Storage="_Servicii", ThisKey="ID_Serviciu", OtherKey="ID_Serviciu", IsForeignKey=true)]
		public Servicii Servicii
		{
			get
			{
				return this._Servicii.Entity;
			}
			set
			{
				Servicii previousValue = this._Servicii.Entity;
				if (((previousValue != value) 
							|| (this._Servicii.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Servicii.Entity = null;
						previousValue.Programaris.Remove(this);
					}
					this._Servicii.Entity = value;
					if ((value != null))
					{
						value.Programaris.Add(this);
						this._ID_Serviciu = value.ID_Serviciu;
					}
					else
					{
						this._ID_Serviciu = default(Nullable<int>);
					}
					this.SendPropertyChanged("Servicii");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Istoric_Clientis(Istoric_Clienti entity)
		{
			this.SendPropertyChanging();
			entity.Programari = this;
		}
		
		private void detach_Istoric_Clientis(Istoric_Clienti entity)
		{
			this.SendPropertyChanging();
			entity.Programari = null;
		}
		
		private void attach_Preferintes(Preferinte entity)
		{
			this.SendPropertyChanging();
			entity.Programari = this;
		}
		
		private void detach_Preferintes(Preferinte entity)
		{
			this.SendPropertyChanging();
			entity.Programari = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Angajati_Functii_Departamente")]
	public partial class Angajati_Functii_Departamente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _ID_Angajat;
		
		private System.Nullable<int> _ID_Functie;
		
		private System.Nullable<int> _ID_Departament;
		
		private int _ID_Relatie;
		
		private EntityRef<Angajati> _Angajati;
		
		private EntityRef<Departamente> _Departamente;
		
		private EntityRef<Functii> _Functii;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_AngajatChanging(System.Nullable<int> value);
    partial void OnID_AngajatChanged();
    partial void OnID_FunctieChanging(System.Nullable<int> value);
    partial void OnID_FunctieChanged();
    partial void OnID_DepartamentChanging(System.Nullable<int> value);
    partial void OnID_DepartamentChanged();
    partial void OnID_RelatieChanging(int value);
    partial void OnID_RelatieChanged();
    #endregion
		
		public Angajati_Functii_Departamente()
		{
			this._Angajati = default(EntityRef<Angajati>);
			this._Departamente = default(EntityRef<Departamente>);
			this._Functii = default(EntityRef<Functii>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Angajat", DbType="Int")]
		public System.Nullable<int> ID_Angajat
		{
			get
			{
				return this._ID_Angajat;
			}
			set
			{
				if ((this._ID_Angajat != value))
				{
					if (this._Angajati.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_AngajatChanging(value);
					this.SendPropertyChanging();
					this._ID_Angajat = value;
					this.SendPropertyChanged("ID_Angajat");
					this.OnID_AngajatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Functie", DbType="Int")]
		public System.Nullable<int> ID_Functie
		{
			get
			{
				return this._ID_Functie;
			}
			set
			{
				if ((this._ID_Functie != value))
				{
					if (this._Functii.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_FunctieChanging(value);
					this.SendPropertyChanging();
					this._ID_Functie = value;
					this.SendPropertyChanged("ID_Functie");
					this.OnID_FunctieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Departament", DbType="Int")]
		public System.Nullable<int> ID_Departament
		{
			get
			{
				return this._ID_Departament;
			}
			set
			{
				if ((this._ID_Departament != value))
				{
					if (this._Departamente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DepartamentChanging(value);
					this.SendPropertyChanging();
					this._ID_Departament = value;
					this.SendPropertyChanged("ID_Departament");
					this.OnID_DepartamentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Relatie", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Relatie
		{
			get
			{
				return this._ID_Relatie;
			}
			set
			{
				if ((this._ID_Relatie != value))
				{
					this.OnID_RelatieChanging(value);
					this.SendPropertyChanging();
					this._ID_Relatie = value;
					this.SendPropertyChanged("ID_Relatie");
					this.OnID_RelatieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Angajati_Angajati_Functii_Departamente", Storage="_Angajati", ThisKey="ID_Angajat", OtherKey="ID_Angajat", IsForeignKey=true)]
		public Angajati Angajati
		{
			get
			{
				return this._Angajati.Entity;
			}
			set
			{
				Angajati previousValue = this._Angajati.Entity;
				if (((previousValue != value) 
							|| (this._Angajati.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Angajati.Entity = null;
						previousValue.Angajati_Functii_Departamentes.Remove(this);
					}
					this._Angajati.Entity = value;
					if ((value != null))
					{
						value.Angajati_Functii_Departamentes.Add(this);
						this._ID_Angajat = value.ID_Angajat;
					}
					else
					{
						this._ID_Angajat = default(Nullable<int>);
					}
					this.SendPropertyChanged("Angajati");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamente_Angajati_Functii_Departamente", Storage="_Departamente", ThisKey="ID_Departament", OtherKey="ID_departament", IsForeignKey=true)]
		public Departamente Departamente
		{
			get
			{
				return this._Departamente.Entity;
			}
			set
			{
				Departamente previousValue = this._Departamente.Entity;
				if (((previousValue != value) 
							|| (this._Departamente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Departamente.Entity = null;
						previousValue.Angajati_Functii_Departamentes.Remove(this);
					}
					this._Departamente.Entity = value;
					if ((value != null))
					{
						value.Angajati_Functii_Departamentes.Add(this);
						this._ID_Departament = value.ID_departament;
					}
					else
					{
						this._ID_Departament = default(Nullable<int>);
					}
					this.SendPropertyChanged("Departamente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Functii_Angajati_Functii_Departamente", Storage="_Functii", ThisKey="ID_Functie", OtherKey="ID_Functie", IsForeignKey=true)]
		public Functii Functii
		{
			get
			{
				return this._Functii.Entity;
			}
			set
			{
				Functii previousValue = this._Functii.Entity;
				if (((previousValue != value) 
							|| (this._Functii.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Functii.Entity = null;
						previousValue.Angajati_Functii_Departamentes.Remove(this);
					}
					this._Functii.Entity = value;
					if ((value != null))
					{
						value.Angajati_Functii_Departamentes.Add(this);
						this._ID_Functie = value.ID_Functie;
					}
					else
					{
						this._ID_Functie = default(Nullable<int>);
					}
					this.SendPropertyChanged("Functii");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
